/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.aurora;

import java.util.Scanner;

public class BoletimEstudantil {

    public static void main(String[] args) {
        int MediaFinal;

        Scanner sc = new Scanner(System.in);
        System.out.println("Insira a Media Final do Aluno:");
        MediaFinal = Integer.parseInt(sc.nextLine());
        sc.close();

        if (MediaFinal < 6) {
            System.out.println("O Aluno foi reprovado!");
        }

        if (MediaFinal == 6)
            System.out.println("O Aluno ficou de recuperação!");

        if (MediaFinal > 6)
            System.out.println("O Aluno foi aprovado!");
    }
}
